import { inter } from "@/styles/fonts";
import "@/styles/globals.scss";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Jim Alley",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}